# -*- coding: utf-8 -*-
"""
Created on Wed Sep  1 15:41:33 2021

@author: ntrup

Odds on where Louisiana Tech's record lands, from ESPN's FPI game projections.

Each run makes the posted PNG and updates a page in html/fbRecordPredictor/ that
keeps every run of the season, so the odds can be followed week to week. Re-running
on the same day replaces that day's run. The run history is kept in
csv/fbRecordPredictorRuns.js; page templates live in lib/html/fbRecordPredictor/.

Run from the repo root:

    python fbRecordPredictor.py                 # this season, PNG + page
    python fbRecordPredictor.py --year 2025     # a past season
    python fbRecordPredictor.py --no-html       # just the PNG
"""

####
# IMPORTS
####

import json
import os
import shutil
from datetime import datetime
from string import Template

import matplotlib.pyplot as plt
import matplotlib.patheffects as pe
import numpy as np
import requests
from html import escape as html_escape
from PIL import Image

from lib.fbCommon import (LOGO_DIR, assetSlug, downloadLogo, gameDateTime, getTeamInfo,
                          previewMetaTags, publishAsset, readJsGlobal, trimmedLogo,
                          writeJsGlobal)

####
# CONSTANTS
####

TEAM_ID = "2348"                       # Louisiana Tech, on ESPN
BOWL_WINS = 6                          # wins needed to be bowl eligible

# ESPN endpoints
ESPN_SCHEDULE_URL = 'https://site.api.espn.com/apis/site/v2/sports/football/college-football/teams/{}/schedule'
ESPN_SUMMARY_URL = 'http://site.api.espn.com/apis/site/v2/sports/football/college-football/summary?event={}'

# Site and file locations
HOME_URL = "https://gtpdd.dog"
SITE_URL = "https://recordpredictor.gtpdd.dog"  # the published root of html/fbRecordPredictor/
SITE_TITLE = "gtpdd's Record Predictor"
TWITTER_HANDLE = "@gotechplsdntdie"

HTML_DIR = "html/fbRecordPredictor"
# html/fbRecordPredictor/ is the site root, so the page and everything it links to live there
WEB_IMG_DIR = os.path.join(HTML_DIR, 'img')
PAGE_TO_ROOT = ''
GTPDD_LOGO = 'img/gtpdd_logo.png'      # the nav logo, published alongside the page
WEB_LOGO_DIR = os.path.join(HTML_DIR, 'logo')
# Opponent logos are ESPN's standard (light-background) logos, shared with fbPlaychart's cache
LOGO_HEIGHT = 56                       # published at 2x the height the table draws
PAGE_FILENAME = 'index.html'
CSS_FILENAME = 'fbRecordPredictor.css'
JS_FILENAME = 'fbRecordPredictor.js'
RUNS_FILENAME = 'runs.js'              # every run of every season, as a script
RUNS_PATH = 'csv/fbRecordPredictorRuns.js'  # tracked master copy of the run history, copied to the site
JS_GLOBAL = 'GTPDD_RECORD_RUNS'
PREVIEW_FILENAME = 'preview.jpg'       # a photo card: JPEG is a sixth of the PNG
PREVIEW_SIZE = (1200, 630)             # a summary_large_image card
PREVIEW_BG = (0, 48, 135)              # the page plane, behind a chart that doesn't fill the card

# Comment block written at the top of runs.js
RUNS_JS_HEADER = """\
// Every run of the record predictor, oldest first within a season. One entry per
// run: the win-total distribution ESPN's FPI implied that day, plus the schedule
// it was built from. Loaded as a plain script so the page works over file:// too.
//
// Generated by fbRecordPredictor.py -- rerun it to add today's run."""

# Page skeleton, stylesheet and script live in lib/html/fbRecordPredictor/
TEMPLATE_DIR = 'lib/html/fbRecordPredictor'
PAGE_TEMPLATE = os.path.join(TEMPLATE_DIR, 'page.html')
PAGE_CSS = os.path.join(TEMPLATE_DIR, CSS_FILENAME)
PAGE_JS = os.path.join(TEMPLATE_DIR, JS_FILENAME)


####
# ESPN FEEDS
####

def espnJson(url):
    # GETs an ESPN endpoint and returns the parsed JSON
    r = requests.get(url, timeout=20)
    r.raise_for_status()
    return r.json()


def seasonSchedule(teamID=TEAM_ID, year=None):
    # Returns (season year, games oldest first), with what's needed to score and display each game
    url = ESPN_SCHEDULE_URL.format(teamID)
    if year:
        url += f'?season={year}'
    x = espnJson(url)
    season = (x.get('requestedSeason') or x.get('season') or {}).get('year')
    season = int(season or year or datetime.now().year)

    games = []
    # Find our side and the opponent's side of each game
    for event in x.get('events', []):
        comp = (event.get('competitions') or [{}])[0]
        us = them = None
        for c in comp.get('competitors', []):
            if str(c.get('team', {}).get('id')) == str(teamID):
                us = c
            else:
                them = c
        if us is None or them is None:
            continue

        completed = bool(((comp.get('status') or {}).get('type') or {}).get('completed'))
        pf = (us.get('score') or {}).get('value')
        pa = (them.get('score') or {}).get('value')
        games.append({
            'gameID': str(event.get('id')),
            'startDate': comp.get('date') or event.get('date'),
            'opponent': them['team'].get('location') or them['team'].get('displayName'),
            'logoUrl': teamLogoUrl(them['team']),
            'setting': 'Neutral' if comp.get('neutralSite')
                       else ('Home' if us.get('homeAway') == 'home' else 'Away'),
            'completed': completed,
            # Unplayed games show 0-0, so only read the score once the game is final
            'pf': int(pf) if completed and pf is not None else None,
            'pa': int(pa) if completed and pa is not None else None,
        })
    games.sort(key=lambda g: g['startDate'] or '')
    return season, games


def teamLogoUrl(team):
    # Returns ESPN's standard (light-background) logo URL for a team
    logos = team.get('logos') or []
    for wanted in ('default', 'dark'):
        for logo in logos:
            if wanted in (logo.get('rel') or []) and logo.get('href'):
                return logo['href']
    return logos[0].get('href') if logos else None


def publishOpponentLogo(name, url):
    # Caches an opponent's logo and publishes a table-sized copy; returns its page link or None
    if not name or not url:
        return None
    slug = assetSlug(name)
    src = os.path.join(LOGO_DIR, f"{name}.png")
    if not os.path.isfile(src) and not downloadLogo(url, src, name):
        return None
    img = trimmedLogo(src)
    if img is None:
        return None
    # Shrink to table size, allowing wide wordmarks up to 2.5x the height
    img.thumbnail((round(LOGO_HEIGHT * 2.5), LOGO_HEIGHT), Image.LANCZOS)
    os.makedirs(WEB_LOGO_DIR, exist_ok=True)
    img.save(os.path.join(WEB_LOGO_DIR, slug + '.png'))
    return 'logo/' + slug + '.png'


def getPrediction(gameID, teamID=TEAM_ID):
    # Returns Tech's FPI win percentage for a game, or None if ESPN has no projection (e.g. some FCS games)
    try:
        x = espnJson(ESPN_SUMMARY_URL.format(gameID))
        predictor = x['predictor']
    except Exception as e:
        print(f"  No FPI for game {gameID} ({type(e).__name__}: {e}).")
        return None
    # Read the projection from Tech's side of the matchup
    try:
        side = 'homeTeam' if str(predictor['homeTeam']['id']) == str(teamID) else 'awayTeam'
        return float(predictor[side]['gameProjection'])
    except (KeyError, TypeError, ValueError):
        print(f"  No FPI projection for game {gameID}.")
        return None


def gameOdds(games, teamID=TEAM_ID):
    # Sets each game's win odds (1/0/0.5 if played, FPI otherwise) and its source for the page
    for g in games:
        if g['completed'] and g['pf'] is not None and g['pa'] is not None:
            g['odds'] = 1.0 if g['pf'] > g['pa'] else (0.0 if g['pf'] < g['pa'] else 0.5)
            g['source'] = 'final'
            continue
        projection = getPrediction(g['gameID'], teamID)
        if projection is None:
            # No FPI: count it as a coin flip rather than dropping it from the schedule
            g['odds'], g['source'] = 0.5, 'even'
        else:
            g['odds'], g['source'] = round(projection / 100, 4), 'fpi'
    return games


####
# ODDS MATH
####

def winDistribution(odds):
    # Returns P(exactly k wins) for k = 0..len(odds), treating every game as independent
    dist = np.zeros(len(odds) + 1)
    dist[0] = 1.0
    # Fold in each game: a win shifts the odds up one win, a loss leaves them in place
    for i, p in enumerate(odds):
        dist[1:i + 2] = dist[1:i + 2] * (1 - p) + dist[0:i + 1] * p
        dist[0] *= (1 - p)
    return dist


def recordLabels(n):
    # Record labels for every possible finish, e.g. n=12 -> '0-12' ... '12-0'
    return [f"{k}-{n - k}" for k in range(n + 1)]


def teamRecord(games):
    # Tech's current record from the games already played, e.g. '3-2'
    wins = sum(1 for g in games if g.get('source') == 'final' and g['odds'] == 1.0)
    losses = sum(1 for g in games if g.get('source') == 'final' and g['odds'] == 0.0)
    return f"{wins}-{losses}"


####
# CHART & LABELS
####

def gameDayText(game):
    # Kickoff date as 'Sep 5', or blank if unknown
    when = gameDateTime(game)
    return '' if when is None else f"{when:%b} {when.day}"


def runLabel(games, when):
    # Names a run by where it falls in the season ('Before Game 4'), as shown in the run selector
    played = sum(1 for g in games if g['source'] == 'final')
    if played >= len(games):
        return 'Final'
    if played == 0:
        return 'Before Game 1'

    # A run more than a week after the last game, with a bye before the next, is the bye-week run
    last, nxt = gameDateTime(games[played - 1]), gameDateTime(games[played])
    if last and nxt and (nxt.date() - last.date()).days > 8 \
            and (when.date() - last.date()).days > 7:
        return 'After Bye Week'
    return f"Before Game {played + 1}"


def drawChart(dist, records, figPath, backgroundPath, color1, color2, datestring):
    # Draws the posted PNG: the record odds as bars in Tech's ESPN colors, over the stadium photo
    odds = list(dist)
    fig, ax = plt.subplots()
    fig.set_size_inches(20, 10)
    # One bar per record, with its odds above and the record below
    for i, v in enumerate(odds):
        ax.bar(i, v, color='#' + color1, edgecolor='#' + color2, linewidth=3, hatch='x')
        offset = -0.012 if v > .01 else 0.005
        ax.text(i, v + offset, "{:.1%}".format(v), ha='center', fontsize=19, color='white',
                path_effects=[pe.withStroke(linewidth=2, foreground='black')])
        ax.text(i, -0.005, records[i], ha='center', va='top', fontsize=20, color='white',
                path_effects=[pe.withStroke(linewidth=2, foreground='black')])

    ax.set_ylim([0, max(odds) + 0.05])
    ax.axis('off')
    ax.set_title("Using ESPN's FPI | " + str(datestring), fontsize=30, color='black')
    plt.suptitle('Louisiana Tech Record Predictor', fontsize=45, color='black', fontweight='bold')
    os.makedirs(os.path.dirname(figPath) or '.', exist_ok=True)
    fig.savefig(figPath, bbox_inches='tight', pad_inches=0, dpi=100, transparent=True)
    plt.close(fig)

    # Center the transparent chart on the background photo
    img = Image.open(figPath, 'r')
    img_w, img_h = img.size
    background = Image.open(backgroundPath, 'r')
    bg_w, bg_h = background.size
    offset = ((bg_w - img_w) // 2, (bg_h - img_h) // 2)
    background.paste(img, offset, img)
    background.save(figPath)
    return figPath


def writePreviewCard(png_path, dest):
    # Saves the link-preview card: the whole chart on a Tech-blue card, since cropping cuts the record labels
    try:
        img = Image.open(png_path).convert('RGB')
    except Exception as e:
        print(f"Could not read {png_path} ({type(e).__name__}: {e}); the page gets no preview image.")
        return None
    W, H = PREVIEW_SIZE
    scale = min(W / img.width, H / img.height)
    img = img.resize((round(img.width * scale), round(img.height * scale)), Image.LANCZOS)
    card = Image.new('RGB', PREVIEW_SIZE, PREVIEW_BG)
    card.paste(img, ((W - img.width) // 2, (H - img.height) // 2))
    os.makedirs(os.path.dirname(dest) or '.', exist_ok=True)
    card.save(dest, quality=88, optimize=True)
    return os.path.basename(dest)


####
# RUN HISTORY
####

def snapshot(games, dist, when):
    # Packages one run (odds, summary numbers and schedule) as the page reads it
    schedule = []
    # One schedule entry per game, with its logo and final score when available
    for g in games:
        entry = {'date': gameDayText(g), 'opponent': g['opponent'], 'setting': g['setting'],
                 'odds': round(float(g['odds']), 4), 'source': g['source']}
        logo = publishOpponentLogo(g['opponent'], g.get('logoUrl'))
        if logo:
            entry['logo'] = logo
        if g['source'] == 'final':
            entry['pf'], entry['pa'] = g['pf'], g['pa']
        schedule.append(entry)
    return {
        'date': when.strftime('%Y-%m-%d'),
        'label': runLabel(games, when),
        'dateLabel': f"{when:%B} {when.day}, {when.year}",
        'record': teamRecord(games),
        'expectedWins': round(sum(g['odds'] for g in games), 3),
        'bowlOdds': round(float(dist[BOWL_WINS:].sum()), 5),
        'odds': [round(float(v), 5) for v in dist],
        'schedule': schedule,
    }


def runsJs(data):
    # Formats runs.js by hand, one line per odds list and game, so it stays readable and diffs cleanly
    out = ['{',
           '  "years": ' + json.dumps(data['years']) + ',',
           '  "bowlWins": ' + json.dumps(data['bowlWins']) + ',',
           '  "runs": {']
    years = sorted(data['runs'], key=int)
    for yi, year in enumerate(years):
        runs = data['runs'][year]
        out.append('    "%s": [' % year)
        for ri, r in enumerate(runs):
            out += ['      {',
                    '        "date": %s, "label": %s, "dateLabel": %s, "record": %s,'
                    % (json.dumps(r['date']), json.dumps(r['label']),
                       json.dumps(r['dateLabel']), json.dumps(r['record'])),
                    '        "expectedWins": %s, "bowlOdds": %s,'
                    % (json.dumps(r['expectedWins']), json.dumps(r['bowlOdds'])),
                    '        "odds": ' + json.dumps(r['odds']) + ',',
                    '        "schedule": [']
            for gi, g in enumerate(r['schedule']):
                out.append('          ' + json.dumps(g)
                           + (',' if gi < len(r['schedule']) - 1 else ''))
            out += ['        ]', '      }' + (',' if ri < len(runs) - 1 else '')]
        out.append('    ]' + (',' if yi < len(years) - 1 else ''))
    out += ['  }', '}']
    return '\n'.join(out)


def normalizeRun(run):
    # Fills in fields the page now needs on runs saved by older versions of this script
    run = dict(run)
    run.setdefault('dateLabel', run.get('label') or run.get('date', ''))
    if run.get('label') in (None, run['dateLabel']):
        # Old date-style labels become 'Before Game N' from the run's schedule (bye weeks can't be recovered)
        schedule = run.get('schedule') or []
        played = sum(1 for g in schedule if g.get('source') == 'final')
        run['label'] = 'Final' if played >= len(schedule) else f"Before Game {played + 1}"

    # Add logos published since the run was saved, so older runs show them too
    schedule = []
    for g in run.get('schedule') or []:
        g = dict(g)
        if 'logo' not in g and g.get('opponent'):
            link = 'logo/' + assetSlug(g['opponent']) + '.png'
            if os.path.isfile(os.path.join(HTML_DIR, link)):
                g['logo'] = link
        schedule.append(g)
    run['schedule'] = schedule
    return run


def saveRun(season, run, path=None):
    # Adds this run to the run history, replacing any run from the same day
    path = path or RUNS_PATH
    stored = readJsGlobal(path, JS_GLOBAL) or {}
    # Load every stored run, upgrading older ones on the way
    runs = {str(y): [normalizeRun(r) for r in v]
            for y, v in (stored.get('runs') or {}).items()}

    # Drop any run from the same date, then add this one in date order
    season_runs = [r for r in runs.get(str(season), []) if r.get('date') != run['date']]
    replaced = len(season_runs) < len(runs.get(str(season), []))
    season_runs.append(run)
    season_runs.sort(key=lambda r: r['date'])
    runs[str(season)] = season_runs

    # Rewrite runs.js with seasons newest first
    years = sorted((int(y) for y in runs), reverse=True)
    writeJsGlobal(path, JS_GLOBAL,
                  {'years': years, 'bowlWins': BOWL_WINS, 'runs': runs},
                  header=RUNS_JS_HEADER, dumps=runsJs)
    print(f"{'Replaced' if replaced else 'Added'} the {run['date']} run in {path}: "
          f"{len(season_runs)} runs on file for {season}")
    return path


####
# WEB PAGE
####

def writeSite(season, run, figPath):
    # Writes the page, its CSS/JS and link-preview card; run data lives in runs.js, not the page
    os.makedirs(HTML_DIR, exist_ok=True)
    shutil.copyfile(PAGE_CSS, os.path.join(HTML_DIR, CSS_FILENAME))
    shutil.copyfile(PAGE_JS, os.path.join(HTML_DIR, JS_FILENAME))
    # Publish the run history the page draws from
    if os.path.isfile(RUNS_PATH):
        shutil.copyfile(RUNS_PATH, os.path.join(HTML_DIR, RUNS_FILENAME))

    preview = writePreviewCard(figPath, os.path.join(HTML_DIR, PREVIEW_FILENAME))
    # gtpdd logo for the nav button and the browser tab icon
    gtpdd_href = publishAsset(GTPDD_LOGO, WEB_IMG_DIR, PAGE_TO_ROOT)
    logo_img = ("<img class='navlogo' src='" + html_escape(gtpdd_href, quote=True)
                + "' alt='gtpdd'>") if gtpdd_href else ""
    icon = ("<link rel='icon' href='" + html_escape(gtpdd_href, quote=True) + "'>\n"
            if gtpdd_href else "")

    # Link-preview title and description
    card_title = f"Louisiana Tech Record Predictor | {season}"
    card_description = (
        f"ESPN's FPI gives Louisiana Tech a {run['bowlOdds']:.1%} shot at a bowl. "
        f"Odds on every possible {season} record, run by run since the season started.")
    page_url = SITE_URL + '/'
    card_image = f"{SITE_URL}/{preview}" if preview else None

    # Fill the page template, escaping plain text
    esc = lambda text: html_escape(str(text), quote=True)
    with open(PAGE_TEMPLATE) as f:
        template = Template(f.read())
    # substitute, not safe_substitute: an unfilled placeholder fails the run instead of shipping
    page = template.substitute(
        title=esc(card_title),
        headLinks=(previewMetaTags(card_title, card_description, page_url, card_image,
                                   twitter_handle=TWITTER_HANDLE) + icon).rstrip('\n'),
        cssHref=esc(CSS_FILENAME),
        homeUrl=esc(HOME_URL),
        logoImg=logo_img,
        siteTitle=esc(SITE_TITLE),
        runsSrc=esc(RUNS_FILENAME),
        jsSrc=esc(JS_FILENAME),
    )
    html_path = os.path.join(HTML_DIR, PAGE_FILENAME)
    with open(html_path, 'w') as f:
        f.write(page)
    print(f"Wrote {html_path}")
    return html_path


####
# MAIN
####

def fbRecordPredictor(platform='AWS', year=None, html=True, teamID=TEAM_ID):
    # Output and background paths differ between the AWS box and Windows
    if platform == 'Windows':
        figPath = r'out_files/fbRecordPredictor.png'
        backgroundPath = r'in_files\backgrounds\fbRecordPredictor.png'
    else:
        figPath = 'out/fbRecordPredictor.png'
        backgroundPath = 'img/fbRecordPredictorBackground.png'

    # Pull the schedule and every game's win odds
    season, games = seasonSchedule(teamID, year)
    if not games:
        print(f"ESPN lists no {season} games for team {teamID}; nothing to predict.")
        return None
    print(f"{season}: {len(games)} games on the schedule")

    gameOdds(games, teamID)
    # Print each game's result or odds
    for g in games:
        played = g['source'] == 'final'
        print(f"  {gameDayText(g):>7}  {g['opponent'][:26]:<26} {g['setting']:<7} "
              + (f"{g['pf']}-{g['pa']}" if played else f"{g['odds']:.1%}"
                 + ('' if g['source'] == 'fpi' else ' (no FPI, held even)')))

    # Combine the game odds into odds for every final record
    dist = winDistribution([g['odds'] for g in games])
    records = recordLabels(len(games))
    now = datetime.now()
    run = snapshot(games, dist, now)

    # Posted PNG, using Tech's ESPN colors
    drawChart(dist, records, figPath, backgroundPath,
              *getTeamInfo(teamID)[1:], now.strftime("%B %d, %Y"))
    print(f"Wrote {figPath}")

    # File this run and rebuild the page
    if html:
        saveRun(season, run)
        writeSite(season, run, figPath)

    # Caption for the post, with bowl odds unless they're already 0% or 100%
    status = ("Using ESPN's FPI, here are the odds on how Tech's record will look "
              "at the end of the regular season")
    if 0 < run['bowlOdds'] < 1:
        status += (". Right now ESPN gives Tech a " + f"{run['bowlOdds']:.2%}"
                   + " chance to make a bowl game:")
    print(status)
    return run


####
# COMMAND LINE
####

if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(
        description="Odds on Louisiana Tech's final record, as a PNG and a page "
                    "that keeps every run of the season.")
    parser.add_argument("--year", type=int,
                        help="Season to run (default: whatever season ESPN is on)")
    parser.add_argument("--platform", default="AWS", choices=["AWS", "Windows"],
                        help="Where the output files go (default: AWS)")
    parser.add_argument("--no-html", action="store_true",
                        help="Only draw the PNG; leave the page and runs.js alone")
    args = parser.parse_args()

    fbRecordPredictor(platform=args.platform, year=args.year, html=not args.no_html)
