# -*- coding: utf-8 -*-
"""
Keeps the game table for the Tech Luck test current. The test scores how Tech did
in the games a fan attended, using one row per completed game: date, opponent,
home/away/neutral and the final score.

The table's master copy is csv/fbTechLuckGames.js. Seasons already in it are left
alone (1988-2019 were hand-collected), so only missing seasons, or seasons that have
gained games, are pulled from CFBD. Each run publishes the table to the site as
html/fbTechLuck/games.js and restores any missing site files from lib/html/fbTechLuck/.

Run from the repo root:

    python fbTechLuck.py                 # add whatever is missing
    python fbTechLuck.py --dry-run       # say what would change, write nothing
    python fbTechLuck.py --year 2026     # just that season
    python fbTechLuck.py --refresh 2026  # rebuild that season from CFBD
"""

####
# IMPORTS
####

import json
import os
import shutil

from dotenv import load_dotenv

from lib.common import copyMissingFiles
from lib.fbCommon import (currentSeason, gameDateText, getGames, loadVenues,
                          localDateTime, readJsGlobal, writeJsGlobal)

# Pull the CFBD API key and other settings from .env
load_dotenv()

####
# CONSTANTS
####

TEAM = 'Louisiana Tech'
GAMES_PATH = 'csv/fbTechLuckGames.js'   # tracked master copy of the game table
SITE_DIR = 'html/fbTechLuck'
GAMES_JS = os.path.join(SITE_DIR, 'games.js')  # the copy the site loads
# Hand-made site files (pages, CSS, JS, icon), copied to the site when missing
STATIC_DIR = 'lib/html/fbTechLuck/static'
JS_GLOBAL = 'TECH_LUCK_GAMES'
FIRST_SEASON = 1988               # as far back as the hand-collected rows go

# Comment block written at the top of games.js
GAMES_JS_HEADER = """\
// Season-by-season results for the Tech Luck test.
// One entry per game, in schedule order. `setting` is Home | Away | Neutral,
// `result` is Win | Loss | Tie, and pf/pa are Tech's points for / against.
// Loaded as a plain script so the pages work over file:// as well as http(s).
//
// Generated by fbTechLuck.py -- rerun it to pick up new games."""


####
# GAME ROWS
####

def gameRow(game, team, venues):
    # Converts one CFBD game into a games.js row, or None if it can't be scored
    if not game.completed or game.home_points is None or game.away_points is None:
        return None

    home = game.home_team == team
    if not home and game.away_team != team:
        return None  # CFBD returned a game this team didn't play in

    if game.start_date is None:
        print(f"  CFBD has no date for {game.home_team} vs {game.away_team}; skipped.")
        return None

    # Points from Tech's side, and the date in the venue's local time
    pf = int(game.home_points if home else game.away_points)
    pa = int(game.away_points if home else game.home_points)
    when = localDateTime(game.start_date, (venues.get(game.venue_id) or {}).get('timezone'))

    return {
        'date': gameDateText(when),
        'opponent': game.away_team if home else game.home_team,
        'setting': 'Neutral' if game.neutral_site else ('Home' if home else 'Away'),
        'result': 'Win' if pf > pa else ('Loss' if pf < pa else 'Tie'),
        'pf': pf,
        'pa': pa,
    }


def seasonRows(year, team, venues):
    # Every completed game of a season, in schedule order
    rows = [gameRow(g, team, venues) for g in getGames(year, team)]
    return [r for r in rows if r]


def gamesJs(seasons):
    # Formats the season table by hand with one game per line, so games.js stays readable in a diff
    years = sorted(seasons)
    out = ['{']
    for yi, year in enumerate(years):
        games = seasons[year]
        out.append(f'  "{year}": [')
        # One line per game, with a trailing comma on all but the last
        for gi, g in enumerate(games):
            out.append('    { "date": %s, "opponent": %s, "setting": %s, "result": %s, '
                       '"pf": %d, "pa": %d }%s'
                       % (json.dumps(g['date']), json.dumps(g['opponent']),
                          json.dumps(g['setting']), json.dumps(g['result']),
                          g['pf'], g['pa'], ',' if gi < len(games) - 1 else ''))
        out.append('  ]' + (',' if yi < len(years) - 1 else ''))
    out.append('}')
    return '\n'.join(out)


####
# PUBLISHING
####

def publishSite(path=GAMES_PATH):
    # Copies the game table to the site and restores any missing site files
    os.makedirs(SITE_DIR, exist_ok=True)
    if os.path.isfile(path):
        shutil.copyfile(path, GAMES_JS)
    copyMissingFiles(STATIC_DIR, SITE_DIR)


####
# MAIN
####

def fbTechLuck(team=TEAM, path=GAMES_PATH, years=None, refresh=(), dryRun=False,
               firstSeason=FIRST_SEASON, today=None):
    # Load the current table and report its size
    existing = readJsGlobal(path, JS_GLOBAL) or {}
    if existing:
        print(f"{path}: {len(existing)} seasons, "
              f"{sum(len(v) for v in existing.values())} games")
    else:
        print(f"{path}: no table yet, building one from {firstSeason}")

    # Seasons to look at: the ones asked for, or every season through the current one
    seasons = {str(y): list(rows) for y, rows in existing.items()}
    wanted = [int(y) for y in years] if years else \
        list(range(firstSeason, currentSeason(today) + 1))
    refresh = {int(y) for y in refresh}

    venues = loadVenues()
    added = updated = 0
    for year in sorted(wanted):
        key = str(year)
        have = seasons.get(key)
        forced = year in refresh

        # Seasons on file are only replaced if CFBD has more games or --refresh asks for it
        if have and not forced:
            rows = seasonRows(year, team, venues)
            if len(rows) == len(have):
                continue
            if len(rows) < len(have):
                print(f"  {year}: kept ({len(have)} games on file, CFBD lists {len(rows)}; "
                      f"run --refresh {year} to take CFBD's version)")
                continue
        else:
            rows = seasonRows(year, team, venues)

        if not rows:
            continue  # season hasn't been played yet

        # Report and store the new or updated season
        if have:
            print(f"  {year}: {len(have)} -> {len(rows)} games"
                  + (" (rebuilt)" if forced else f" (+{len(rows) - len(have)})"))
            updated += 1
        else:
            print(f"  {year}: added, {len(rows)} games")
            added += 1
        seasons[key] = rows

    # Write the table if anything changed, unless this is a dry run
    if not added and not updated:
        print("Everything is already up to date.")
    elif dryRun:
        print(f"Dry run: {added} season(s) would be added, {updated} updated. "
              f"{path} left alone.")
    else:
        writeJsGlobal(path, JS_GLOBAL, seasons, header=GAMES_JS_HEADER,
                      dumps=lambda data: gamesJs(data))
        print(f"Wrote {path}: {len(seasons)} seasons, "
              f"{sum(len(v) for v in seasons.values())} games "
              f"({added} added, {updated} updated)")

    # Publish to the site on every real run, so a missing copy comes back even with no new games
    if not dryRun:
        publishSite(path)
    return path


####
# COMMAND LINE
####

if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(
        description="Add any missing games to the Tech Luck table and publish it to the site.")
    parser.add_argument("--team", default=TEAM, help=f"CFBD team name (default: {TEAM})")
    parser.add_argument("--year", type=int, nargs='+',
                        help="Only look at these seasons (default: every season "
                             f"from {FIRST_SEASON} to the current one)")
    parser.add_argument("--refresh", type=int, nargs='+', default=[],
                        help="Rebuild these seasons from CFBD even if they look complete")
    parser.add_argument("--dry-run", action="store_true",
                        help="Report what would change without writing or publishing anything")
    args = parser.parse_args()

    fbTechLuck(team=args.team, years=args.year, refresh=args.refresh, dryRun=args.dry_run)
