// Every run of the record predictor, oldest first within a season. One entry per
// run: the win-total distribution ESPN's FPI implied that day, plus the schedule
// it was built from. Loaded as a plain script so the page works over file:// too.
//
// Generated by fbRecordPredictor.py -- rerun it to add today's run.
window.GTPDD_RECORD_RUNS = {
  "years": [2026],
  "bowlWins": 6,
  "runs": {
    "2026": [
      {
        "date": "2026-09-04", "label": "Before Game 1", "dateLabel": "September 4, 2026", "record": "0-0",
        "expectedWins": 5.435, "bowlOdds": 0.47957,
        "odds": [2e-05, 0.00218, 0.01923, 0.0759, 0.17281, 0.25029, 0.24035, 0.15439, 0.06511, 0.01708, 0.00248, 0.00015, 0.0],
        "schedule": [
          {"date": "Sep 5", "opponent": "Northwestern State", "setting": "Home", "odds": 0.99, "source": "fpi", "logo": "logo/Northwestern_State.png"},
          {"date": "Sep 12", "opponent": "LSU", "setting": "Away", "odds": 0.02, "source": "fpi", "logo": "logo/LSU.png"},
          {"date": "Sep 19", "opponent": "Baylor", "setting": "Away", "odds": 0.096, "source": "fpi", "logo": "logo/Baylor.png"},
          {"date": "Oct 2", "opponent": "Army", "setting": "Home", "odds": 0.505, "source": "fpi", "logo": "logo/Army.png"},
          {"date": "Oct 9", "opponent": "Louisiana", "setting": "Home", "odds": 0.521, "source": "fpi", "logo": "logo/Louisiana.png"},
          {"date": "Oct 16", "opponent": "UL Monroe", "setting": "Away", "odds": 0.697, "source": "fpi", "logo": "logo/UL_Monroe.png"},
          {"date": "Oct 23", "opponent": "Old Dominion", "setting": "Home", "odds": 0.426, "source": "fpi", "logo": "logo/Old_Dominion.png"},
          {"date": "Oct 30", "opponent": "South Alabama", "setting": "Away", "odds": 0.45, "source": "fpi", "logo": "logo/South_Alabama.png"},
          {"date": "Nov 6", "opponent": "Troy", "setting": "Away", "odds": 0.362, "source": "fpi", "logo": "logo/Troy.png"},
          {"date": "Nov 13", "opponent": "Southern Miss", "setting": "Home", "odds": 0.419, "source": "fpi", "logo": "logo/Southern_Miss.png"},
          {"date": "Nov 20", "opponent": "Arkansas State", "setting": "Home", "odds": 0.551, "source": "fpi", "logo": "logo/Arkansas_State.png"},
          {"date": "Nov 27", "opponent": "Georgia Southern", "setting": "Away", "odds": 0.398, "source": "fpi", "logo": "logo/Georgia_Southern.png"}
        ]
      },
      {
        "date": "2026-09-10", "label": "Before Game 2", "dateLabel": "September 10, 2026", "record": "1-0",
        "expectedWins": 6.393, "bowlOdds": 0.72839,
        "odds": [0.0, 0.00018, 0.00302, 0.02048, 0.07573, 0.17219, 0.25383, 0.24627, 0.15484, 0.05981, 0.01256, 0.00107, 2e-05],
        "schedule": [
          {"date": "Sep 5", "opponent": "Northwestern State", "setting": "Home", "odds": 1.0, "source": "final", "logo": "logo/Northwestern_State.png", "pf": 80, "pa": 6},
          {"date": "Sep 12", "opponent": "LSU", "setting": "Away", "odds": 0.019, "source": "fpi", "logo": "logo/LSU.png"},
          {"date": "Sep 19", "opponent": "Baylor", "setting": "Away", "odds": 0.133, "source": "fpi", "logo": "logo/Baylor.png"},
          {"date": "Oct 2", "opponent": "Army", "setting": "Home", "odds": 0.5, "source": "fpi", "logo": "logo/Army.png"},
          {"date": "Oct 9", "opponent": "Louisiana", "setting": "Home", "odds": 0.582, "source": "fpi", "logo": "logo/Louisiana.png"},
          {"date": "Oct 16", "opponent": "UL Monroe", "setting": "Away", "odds": 0.87, "source": "fpi", "logo": "logo/UL_Monroe.png"},
          {"date": "Oct 23", "opponent": "Old Dominion", "setting": "Home", "odds": 0.586, "source": "fpi", "logo": "logo/Old_Dominion.png"},
          {"date": "Oct 30", "opponent": "South Alabama", "setting": "Away", "odds": 0.531, "source": "fpi", "logo": "logo/South_Alabama.png"},
          {"date": "Nov 6", "opponent": "Troy", "setting": "Away", "odds": 0.522, "source": "fpi", "logo": "logo/Troy.png"},
          {"date": "Nov 13", "opponent": "Southern Miss", "setting": "Home", "odds": 0.465, "source": "fpi", "logo": "logo/Southern_Miss.png"},
          {"date": "Nov 20", "opponent": "Arkansas State", "setting": "Home", "odds": 0.7, "source": "fpi", "logo": "logo/Arkansas_State.png"},
          {"date": "Nov 27", "opponent": "Georgia Southern", "setting": "Away", "odds": 0.485, "source": "fpi", "logo": "logo/Georgia_Southern.png"}
        ]
      },
      {
        "date": "2026-09-17", "label": "Before Game 3", "dateLabel": "September 17, 2026", "record": "1-1",
        "expectedWins": 6.164, "bowlOdds": 0.67404,
        "odds": [0.0, 0.00034, 0.00491, 0.02914, 0.09581, 0.19576, 0.26082, 0.22923, 0.13028, 0.04501, 0.00818, 0.00052, 0.0],
        "schedule": [
          {"date": "Sep 5", "opponent": "Northwestern State", "setting": "Home", "odds": 1.0, "source": "final", "logo": "logo/Northwestern_State.png", "pf": 80, "pa": 6},
          {"date": "Sep 12", "opponent": "LSU", "setting": "Away", "odds": 0.0, "source": "final", "logo": "logo/LSU.png", "pf": 14, "pa": 45},
          {"date": "Sep 19", "opponent": "Baylor", "setting": "Away", "odds": 0.11, "source": "fpi", "logo": "logo/Baylor.png"},
          {"date": "Oct 2", "opponent": "Army", "setting": "Home", "odds": 0.508, "source": "fpi", "logo": "logo/Army.png"},
          {"date": "Oct 9", "opponent": "Louisiana", "setting": "Home", "odds": 0.494, "source": "fpi", "logo": "logo/Louisiana.png"},
          {"date": "Oct 16", "opponent": "UL Monroe", "setting": "Away", "odds": 0.837, "source": "fpi", "logo": "logo/UL_Monroe.png"},
          {"date": "Oct 23", "opponent": "Old Dominion", "setting": "Home", "odds": 0.593, "source": "fpi", "logo": "logo/Old_Dominion.png"},
          {"date": "Oct 30", "opponent": "South Alabama", "setting": "Away", "odds": 0.465, "source": "fpi", "logo": "logo/South_Alabama.png"},
          {"date": "Nov 6", "opponent": "Troy", "setting": "Away", "odds": 0.495, "source": "fpi", "logo": "logo/Troy.png"},
          {"date": "Nov 13", "opponent": "Southern Miss", "setting": "Home", "odds": 0.571, "source": "fpi", "logo": "logo/Southern_Miss.png"},
          {"date": "Nov 20", "opponent": "Arkansas State", "setting": "Home", "odds": 0.63, "source": "fpi", "logo": "logo/Arkansas_State.png"},
          {"date": "Nov 27", "opponent": "Georgia Southern", "setting": "Away", "odds": 0.461, "source": "fpi", "logo": "logo/Georgia_Southern.png"}
        ]
      },
      {
        "date": "2026-09-24", "label": "Before BYE", "dateLabel": "September 24, 2026", "record": "1-2",
        "expectedWins": 6.091, "bowlOdds": 0.66338,
        "odds": [0.0, 0.0003, 0.0046, 0.0287, 0.09822, 0.20479, 0.2716, 0.23034, 0.121, 0.03586, 0.00458, 0.0, 0.0],
        "schedule": [
          {"date": "Sep 5", "opponent": "Northwestern State", "setting": "Home", "odds": 1.0, "source": "final", "logo": "logo/Northwestern_State.png", "pf": 80, "pa": 6},
          {"date": "Sep 12", "opponent": "LSU", "setting": "Away", "odds": 0.0, "source": "final", "logo": "logo/LSU.png", "pf": 14, "pa": 45},
          {"date": "Sep 19", "opponent": "Baylor", "setting": "Away", "odds": 0.0, "source": "final", "logo": "logo/Baylor.png", "pf": 19, "pa": 36},
          {"date": "Oct 3", "opponent": "Army", "setting": "Home", "odds": 0.493, "source": "fpi", "logo": "logo/Army.png"},
          {"date": "Oct 9", "opponent": "Louisiana", "setting": "Home", "odds": 0.516, "source": "fpi", "logo": "logo/Louisiana.png"},
          {"date": "Oct 16", "opponent": "UL Monroe", "setting": "Away", "odds": 0.827, "source": "fpi", "logo": "logo/UL_Monroe.png"},
          {"date": "Oct 23", "opponent": "Old Dominion", "setting": "Home", "odds": 0.594, "source": "fpi", "logo": "logo/Old_Dominion.png"},
          {"date": "Oct 30", "opponent": "South Alabama", "setting": "Away", "odds": 0.431, "source": "fpi", "logo": "logo/South_Alabama.png"},
          {"date": "Nov 6", "opponent": "Troy", "setting": "Away", "odds": 0.398, "source": "fpi", "logo": "logo/Troy.png"},
          {"date": "Nov 13", "opponent": "Southern Miss", "setting": "Home", "odds": 0.728, "source": "fpi", "logo": "logo/Southern_Miss.png"},
          {"date": "Nov 20", "opponent": "Arkansas State", "setting": "Home", "odds": 0.657, "source": "fpi", "logo": "logo/Arkansas_State.png"},
          {"date": "Nov 27", "opponent": "Georgia Southern", "setting": "Away", "odds": 0.447, "source": "fpi", "logo": "logo/Georgia_Southern.png"}
        ]
      },
      {
        "date": "2026-10-02", "label": "After Bye Week", "dateLabel": "October 2, 2026", "record": "1-2",
        "expectedWins": 6.245, "bowlOdds": 0.70323,
        "odds": [0.0, 0.00019, 0.00324, 0.02232, 0.0832, 0.18782, 0.26872, 0.2454, 0.13874, 0.04427, 0.0061, 0.0, 0.0],
        "schedule": [
          {"date": "Sep 5", "opponent": "Northwestern State", "setting": "Home", "odds": 1.0, "source": "final", "logo": "logo/Northwestern_State.png", "pf": 80, "pa": 6},
          {"date": "Sep 12", "opponent": "LSU", "setting": "Away", "odds": 0.0, "source": "final", "logo": "logo/LSU.png", "pf": 14, "pa": 45},
          {"date": "Sep 19", "opponent": "Baylor", "setting": "Away", "odds": 0.0, "source": "final", "logo": "logo/Baylor.png", "pf": 19, "pa": 36},
          {"date": "Oct 3", "opponent": "Army", "setting": "Home", "odds": 0.49, "source": "fpi", "logo": "logo/Army.png"},
          {"date": "Oct 10", "opponent": "Louisiana", "setting": "Home", "odds": 0.447, "source": "fpi", "logo": "logo/Louisiana.png"},
          {"date": "Oct 16", "opponent": "UL Monroe", "setting": "Away", "odds": 0.865, "source": "fpi", "logo": "logo/UL_Monroe.png"},
          {"date": "Oct 23", "opponent": "Old Dominion", "setting": "Home", "odds": 0.676, "source": "fpi", "logo": "logo/Old_Dominion.png"},
          {"date": "Oct 30", "opponent": "South Alabama", "setting": "Away", "odds": 0.484, "source": "fpi", "logo": "logo/South_Alabama.png"},
          {"date": "Nov 6", "opponent": "Troy", "setting": "Away", "odds": 0.483, "source": "fpi", "logo": "logo/Troy.png"},
          {"date": "Nov 13", "opponent": "Southern Miss", "setting": "Home", "odds": 0.701, "source": "fpi", "logo": "logo/Southern_Miss.png"},
          {"date": "Nov 20", "opponent": "Arkansas State", "setting": "Home", "odds": 0.656, "source": "fpi", "logo": "logo/Arkansas_State.png"},
          {"date": "Nov 27", "opponent": "Georgia Southern", "setting": "Away", "odds": 0.443, "source": "fpi", "logo": "logo/Georgia_Southern.png"}
        ]
      },
      {
        "date": "2026-10-08", "label": "Before Game 5", "dateLabel": "October 8, 2026", "record": "2-2",
        "expectedWins": 7.087, "bowlOdds": 0.89189,
        "odds": [0.0, 0.0, 0.00011, 0.00241, 0.01999, 0.08559, 0.20875, 0.29984, 0.25032, 0.11216, 0.02083, 0.0, 0.0],
        "schedule": [
          {"date": "Sep 5", "opponent": "Northwestern State", "setting": "Home", "odds": 1.0, "source": "final", "logo": "logo/Northwestern_State.png", "pf": 80, "pa": 6},
          {"date": "Sep 12", "opponent": "LSU", "setting": "Away", "odds": 0.0, "source": "final", "logo": "logo/LSU.png", "pf": 14, "pa": 45},
          {"date": "Sep 19", "opponent": "Baylor", "setting": "Away", "odds": 0.0, "source": "final", "logo": "logo/Baylor.png", "pf": 19, "pa": 36},
          {"date": "Oct 3", "opponent": "Army", "setting": "Home", "odds": 1.0, "source": "final", "logo": "logo/Army.png", "pf": 31, "pa": 29},
          {"date": "Oct 10", "opponent": "Louisiana", "setting": "Home", "odds": 0.528, "source": "fpi", "logo": "logo/Louisiana.png"},
          {"date": "Oct 18", "opponent": "UL Monroe", "setting": "Away", "odds": 0.888, "source": "fpi", "logo": "logo/UL_Monroe.png"},
          {"date": "Oct 23", "opponent": "Old Dominion", "setting": "Home", "odds": 0.795, "source": "fpi", "logo": "logo/Old_Dominion.png"},
          {"date": "Oct 30", "opponent": "South Alabama", "setting": "Away", "odds": 0.527, "source": "fpi", "logo": "logo/South_Alabama.png"},
          {"date": "Nov 6", "opponent": "Troy", "setting": "Away", "odds": 0.442, "source": "fpi", "logo": "logo/Troy.png"},
          {"date": "Nov 13", "opponent": "Southern Miss", "setting": "Home", "odds": 0.778, "source": "fpi", "logo": "logo/Southern_Miss.png"},
          {"date": "Nov 20", "opponent": "Arkansas State", "setting": "Home", "odds": 0.666, "source": "fpi", "logo": "logo/Arkansas_State.png"},
          {"date": "Nov 27", "opponent": "Georgia Southern", "setting": "Away", "odds": 0.463, "source": "fpi", "logo": "logo/Georgia_Southern.png"}
        ]
      }
    ]
  }
};
